Messages:
  No-perms: '&cYou are not permitted to use that command.'
  No-Conduit: '&6You need a SpawnerConduit to use that'
  No-Arguments: '&cPlease specify an argument.'
  Invalid-Player: '&cPlease specify a valid player'
  Received: '&6You received a conduit.'
  Unknown-Arg: '&6Unknown Argument'
  Place-Conduit: '&cYou are not allowed to place that!'
  Spawner-Received: '&6You have been given a mob spawner!'