Spawner:
  Name: '&6{MOB} &eSpawner'

# Can be given with /givespawner

# NOTE: ALL VALUES BELOW HERE, MUST BE IN CAPITAL LETTERS, WITH UNDERSCORES BETWEEN WORDS.
Mobs:
  - SHEEP
  - COW

# Cannot be mined
DisabledSpawners:
  - BLAZE
  - WITHER

Messages:
  No-perms: '&cYou are not permitted to use that command.'
  No-Conduit: '&6You need a SpawnerConduit to use that'
  No-Arguments: '&cPlease specify an argument.'
  Invalid-Player: '&cPlease specify a valid player'
  Invalid-Mob: '&cPlease specify a valid mob.'
  Received: '&6You received a conduit.'
  Unknown-Arg: '&6Unknown Argument'
  Place-Conduit: '&cYou are not allowed to place that!'
  Spawner-Received: '&6You have been given a mob spawner!'
  No-Conduit1: '&6You need a SpawnerConduit to mine that!'
  No-Conduit2: '&6You can buy them on /shop'
  Cannot-Rename: '&cYou are not allowed to rename spawners in an anvil!'
  Cant-Mine: '&cYou are not permitted to mine that.'
  Usage: '/<command> give <player> <MOB>'
  Disabled: '&cYou are not allowed to mine that spawner!'