spawnerName: '<gold>{MOB} <yellow>Spawner'
tokenName: '<gold>Spawner Token'
tokenMaterial: 'CONDUIT'

# Can be given with /givespawner
# NOTE: ALL VALUES BELOW HERE, MUST BE IN CAPITAL LETTERS, WITH UNDERSCORES BETWEEN WORDS.
spawners-for-givespawner:
  - SHEEP
  - COW

# Cannot be mined
unminable-spawners:
  - BLAZE
  - WITHER

messages:
  usageFormat: '/<command> give <player> <mob>'
  noPerms: '<red>You are not permitted to use that command.'
  noToken: '<red>You need a Spawner Token to use that'
  noArguments: '<red>Please specify an argument.'
  invalidPlayer: '<red>Please specify a valid player'
  invalidMob: '<red>Please specify a valid mob.'
  tokenReceived: '<green>You received a Spawner Token!'
  spawnerReceived: '<green>You received a Mob Spawner!'
  invalidArgument: '<red>Unknown Argument'
  cannotPlace: '<red>You are not allowed to place that!'
  cannotRename: '<red>You are not permitted to rename that item in an anvil.'
  cannotMine: '<red>You are not permitted to mine that.'
  spawnerPlaced: "<green>You have placed a <yellow>{0}</yellow> Spawner!"